name: Gate

on:
  push:
    branches: 
      - trunk

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.05.0
      
    runs-on: ${{ matrix.os }}      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      
      - name: Build
        run: make mycaml

      - name: Test
        run: make test
